### ISSUE TITLE
Add support for anichart and livechart.

### ISSUE THREAD

**Issue by toprak** [Metacor/nyaa-linker#4]
### Proposal

database sites usually have very complicated charts, these are compact, simple and nice, if you provide support for these two, especially livechart, it would be very excellent.

**Comment by Metacor** [comment]
I didn't know LiveChart also had a /anime database, I thought it was just the calendar, so I'll be adding that in the next update.

For the calendar pages, I have a few questions/concerns about adding support.
- Clicking on the titles will already send you to their respective /anime pages, where the nyaa button will already exist.
- Injecting dozens of context dependent buttons on a single page might cause performance issues (might not be an issue).
- These pages only show the main title, so "romaji"|"english" searches won't be possible, resulting in potentially fewer search results compared to using the button on the main /anime page.

I believe support could still be added for these sites (as for the LiveChart/anime it's going to be added either way), I'm just not sure how much benefit there is compared to just clicking on the title to open the anime page.

**Comment by toprak** [comment]
I guess I was a bit too perfectionist, sorry, I wanted to eliminate it even if there was a small possibility, sometimes those link sections are incomplete, that's why I said that, but in general context you are right, it's nothing more than extra work (I've been sleep deprived for two days, I can't use my head, sorry for the unnecessary issues :D)

**Comment by toprak** [comment]
@Metacor Thanks for adding livechart, it is awesome implementation!
